### ISSUE TITLE
Fix needed for when using this mod with Mineclone2 

### ISSUE THREAD

**Issue by ghost** [veprogames/mt-resizeme#2]
As the title says, we just need a minor fix for this mod when used in Mineclone2 - namely that it works great, but the first person camera view doesn't change to reflect the change in size like it does in a regular Minetest game. An update that fixes this would be great.

**Comment by BramvdnHeuvel** [comment]
Why is this closed? I am stil experiencing this issue and I would love to learn how to fix this.
